### ISSUE TITLE
Enable this action to run from within workflows triggered to run from a tag

### ISSUE THREAD

**Issue by QuintinWillison** [CPC-Systems/github-event-context-action#1]
We tried to run one of our publishing workflows from a tag ref and got:

> Error: this action can only be ran on a pull_request, a push to the 'main' branch, or a push of a tag

Context that was available to the action:

<img width="828" alt="Screenshot 2023-12-29 at 10 26 36" src="https://github.com/CPC-Systems/github-event-context-action/assets/8318344/f81c85cc-3011-4990-a81e-fd4eac103854">

There is clearly enough information there for this action to do something sensible in this scenario.

I've created this issue under this fork of this action as, subsequent to this, my intention is for us to start using this forked action with repositories (both public and private) within [the `CPC-Systems` org.](https://github.com/CPC-Systems).

**Comment by QuintinWillison** [comment]
Should have been fixed by https://github.com/CPC-Systems/github-event-context-action/commit/b10d3589e35ec8528f4c3cd19335781abc0fa41e.

**Comment by QuintinWillison** [comment]
I'm leaving this issue open until we've had opportunity to need to run a workflow against a tag, most likely a [KAD OPR publish](https://github.com/CPC-Systems/KAD-OPR/actions/workflows/publish.yml), which will prove my fix. FYI, @glddata @justinas-marozas.

**Comment by QuintinWillison** [comment]
@glddata Is it ok to close this issue as completed? That is, if you've been able to release from a tag since. 🤔

**Comment by glddata** [comment]
Good point, Yes happy to close as i have release via the Tags
